# Generated by Django 3.2 on 2021-11-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
