# Generated by Django 3.2 on 2021-11-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_receptioniste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptioniste',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
