# Generated by Django 3.2 on 2021-11-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_alter_receptioniste_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='presence',
            field=models.BooleanField(default=False),
        ),
    ]
