# Generated by Django 3.2 on 2021-12-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('occupied', 'occupied'), ('free', 'free')], default='free', max_length=200, null=True),
        ),
    ]
