# Generated by Django 3.2 on 2021-12-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_auto_20211214_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='isAffected',
            field=models.BooleanField(default=False),
        ),
    ]
