# Generated by Django 3.2 on 2021-12-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_patient_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='blockName',
            field=models.CharField(choices=[('Cardiologie', 'Cardiologie'), ('Dermatologie', 'Dermatologie'), ("Médecine d'urgence", "Médecine d'urgence"), ('Allergologie/Immunologie', 'Allergologie/Immunologie'), ('Anesthésiologistes', 'Anesthésiologistes'), ('Chirurgie du côlon et du rectum', 'Chirurgie du côlon et du rectum')], default='Cardiologie', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologie', 'Cardiologie'), ('Dermatologie', 'Dermatologie'), ("Médecine d'urgence", "Médecine d'urgence"), ('Allergologie/Immunologie', 'Allergologie/Immunologie'), ('Anesthésiologistes', 'Anesthésiologistes'), ('Chirurgie du côlon et du rectum', 'Chirurgie du côlon et du rectum')], default='Cardiologie', max_length=50),
        ),
    ]
