# Generated by Django 3.2 on 2021-12-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_bed_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='patientId',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
