# Generated by Django 3.2 on 2021-12-15 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0032_alter_bed_patientid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(choices=[('Infirmier Urgentiste', 'Infirmier Urgentiste'), ('Infirmier Polyvalent', 'Infirmier Polyvalent'), ('Infirmier Anesthésiste', 'Infirmier Anesthésiste'), ('Infirmier Néonatale', 'Infirmier Néonatale'), ('Infirmier en Pédiatrie', 'Infirmier en Pédiatrie'), ('Infirmier Psychiatrique', 'Infirmier Psychiatrique'), ('Infirmier en Traumatologie', 'Infirmier en Traumatologie'), ('Infirmier en soins gérés', 'Infirmier en soins gérés'), ('Infirmière sage-femme', 'Infirmière sage-femme')], default='Cardiologist', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
