# Generated by Django 3.2 on 2021-12-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_infirmier'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date',
            field=models.CharField(default='2021-12-12', max_length=40),
        ),
        migrations.AddField(
            model_name='doctor',
            name='horaire',
            field=models.CharField(default='00:00:00', max_length=40),
        ),
    ]
